apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
   db-password: YWRtaW4=
   username: YWRtaW4=
   password: TWFyZ2VyeUAxMjM=
   rootPassword: YWRtaW4=
   database: VG9kb0FwcA==